version: 2

models:
  - name: stg_stock_prices
    columns:
      - name: symbol
        tests:
          - not_null
      - name: date
        tests:
          - not_null
      - name: close
        tests:
          - not_null
      - name: volume
        tests:
          - not_null
